version : "3.9"

networks:
  rlspfood-network:
    driver: bridge

services:

  rlspfood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    networks:
      - rlspfood-network

  rlspfood-api:
    #build: .
    image: rlspfood:1.0
    command: ["/wait-for-it.sh", "rlspfood-mysql:3306", "-t", "15", "--", "java", "-jar", "rlspfood.jar"]
    environment:
      DB_HOST: rlspfood-mysql
      DP_PORT: 3308
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: rlspfood-redis
      SPRING_PROFILES_ACTIVE: development
    # tiramos a porta para pode fazer rodar 2+ instancias em portas diferentes
    #ports:
    #  - "8080:8080"
    networks:
      - rlspfood-network
    depends_on:
      - rlspfood-mysql

  rlspfood-reverse-proxy-nginx:
    build: ./nginx
    image: rlspfood-nginx
    ports:
      - "80:80"
    networks:
      - rlspfood-network
    depends_on:
      - rlspfood-api
