version : "3.9"

networks:
  rlspfood-network:
    driver: bridge

services:

  rlspfood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    networks:
      - rlspfood-network

  rlspfood-api:
    #build: .
    image: rlspfood:1.0
    command: ["/wait-for-it.sh", "rlspfood-mysql:3308", "-t", "15", "--", "java", "-jar", "rlspfood.jar"]
    environment:
      DB_HOST: rlspfood-mysql
      DP_PORT: 3308
    ports:
      - "8080:8080"
    networks:
      - rlspfood-network
    depends_on:
      - rlspfood-mysql